### ISSUE TITLE
16.4 Gerar wizzard para instalar as dependências do python - lib "pandas"

### ISSUE THREAD

**Issue by Cardoso-CHM** [ronaldoapf/PDS1#103]

**Comment by ronaldoapf** [comment]
Feita no seguinte commit: https://github.com/ronaldoapf/PDS1/commit/b1f79b51c7f716ead0352659e9e51e675f8cf93c

**Comment by ronaldoapf** [comment]
Feita no seguinte commit: https://github.com/ronaldoapf/PDS1/commit/b1f79b51c7f716ead0352659e9e51e675f8cf93c
