### ISSUE TITLE
18.18 Colocar referências da página dos tutoriais nos tooltips da aplicação

### ISSUE THREAD

**Issue by Cardoso-CHM** [ronaldoapf/PDS1#111]

**Comment by JoaoVitorPereiraUFU** [comment]
Task realizada no commit : 91dd5475d851fa5fbe709e4da32d3cbaced80e3d

Link: https://github.com/ronaldoapf/PDS1/commit/91dd5475d851fa5fbe709e4da32d3cbaced80e3d
