### ISSUE TITLE
To do - Ronaldo (24/09)

### ISSUE THREAD

**Issue by Cardoso-CHM** [ronaldoapf/PDS1#17]
## Tarefas a serem realizadas:
- [ ] Verificar condição "Testável" das estórias (Principais estórias - INVEST)
- [x] Verificar condição "Estimável" das estórias (Principais estórias - INVEST)
- [x] Tarefas (Reavaliar hierarquia e dimensões das estórias)
>- [ ] Vejo um problema de hierarquia, a user story 4 necessita da user story 2.
- [ ] Diagrama de atividades e fluxo de execução ou regras de negócio (Modelos complementares para 4 estórias)

**Comment by ronaldoapf** [comment]
- Creio que a dimensão das estórias esteja correta. Não tenho a reavaliar.
- Vejo um problema de hierarquia, a user story 4 necessita da user story 2.
