### ISSUE TITLE
Ajustes na estrutura de pastas

### ISSUE THREAD

**Issue by victor-sobreira** [ronaldoapf/PDS1#2]
Sugiro a seguinte estrutura de pastas para armazenar os artefatos de documentação:

* docs
  * minutas
      * 2019.08.27_14h00m_{identificacao}.md
  * modelos
      * diagrama_casos_de_uso_{identificacao}.png
      * visao_caso_negocio_{identificacao}.md
      * riscos_{identificacao}.md
  * glossario_{identificacao}.md

Onde, {identificacao} pode ser o nome provisório do sistema, nome do contato/colaborador, … Fica a critério do grupo. Só mantenham a consistência e evitem nomes muito compridos, especialmente para pastas.

**Comment by ronaldoapf** [comment]
A estrutura das pastas foram alteradas conforme sugerido

**Comment by victor-sobreira** [comment]
Revejam a estrutura criada pois modelos e glossário fazem parte da pasta docs. Diagramas de caso de uso, riscos, visão e caso de negócio fazem parte da pasta "modelos". Não é necessário usar chaves "{}" na identificação (é só um delimitador para o exemplo).

**Comment by ronaldoapf** [comment]
Modificada a estrutura de arquivos e pastas.
