### ISSUE TITLE
(11.6) Implementar algoritmo em Python para receber o json vindo do front-end e extrair suas informações ( 2 horas )

### ISSUE THREAD

**Issue by JoaoVitorPereiraUFU** [ronaldoapf/PDS1#37]

**Comment by JoaoVitorPereiraUFU** [comment]
@Cardoso-CHM @ronaldoapf @amandadduraes  criei a função carregarPlanilhasArray():, verifiquem se está correto quando puderem

**Comment by JoaoVitorPereiraUFU** [comment]
Ainda não está generico essa leitura, fiz somente com o arquivo base, pois acho melhor testarmos um caso de uso, e depois generalizar

**Comment by ronaldoapf** [comment]
Tarefa foi realizada e revisada com a professora coordenadora.
