### ISSUE TITLE
User Story 14: Criar rotina de uso do sistema para usuário com perfil mais básico

### ISSUE THREAD

**Issue by JoaoVitorPereiraUFU** [ronaldoapf/PDS1#54]
## Como  usuário desejo entrar com planilhas do IBGE e a partir delas conseguir obter informações analísticas, com o intuito de analisar detalhadamente os dados  fornecidos pelo IBGE.

> Existe a necessidade de criar uma rotina de uso para usuários mais leigos na área, para melhor otimização do seu trabalho.

Critérios de Aceitação:
- Sistema lista todas as colunas decodificadas
- Sistema possibilita que o usuário escolha quais colunas ele quer
- Sistema gera figura com gráficos baseados nas planilhas e colunas escolhidas pelo usuário

Tarefas:
- [ ] Alteração do design da interface principal do sistema (1 hora)
- [ ] Implementar interface em HTML para listar as colunas das planilhas escolhidas pelo usuário e selecionar as colunas de interesse ( 1 hora )
- [ ] Implementar algoritmo em Python para enviar ao front-end a planilha que o usuário escolheu (já decodificada) em uma estrutura de dados (1 hora)
- [ ] Editar a estrutura de dados retirando as colunas que não foram marcadas como interessante (1 hora)
- [ ] Implementar algoritmo para enviar a estrutura de dados via json para o back-end (30 minutos)
- [ ] Implementar algoritmo em Python para receber o json, extrair suas informações, realizar o processamento necessário e retornar ao front-end o resultado do processo - positivo ou negativo (30 minutos)
- [ ] Implementar algoritmo para gerar figuras com gráficos a partir das planilhas e colunas selecionadas pelo usuário ( 8 horas)

**Comment by ronaldoapf** [comment]
Biblioteca para gerar gráfico python: bokeh

**Comment by Cardoso-CHM** [comment]
Esta estória deverá ser fechada por motivos de cronograma, não foi possível implementá-la ao decorrer do semestre e não será possível encaixá-la no escopo da ultima sprint (sprint 4). 
Tal fato é uma consequência da baixa prioridade da estória junto com a carência de reuniões com a concedente do projeto.
