### ISSUE TITLE
User Story 15: Criar algoritmo para extrair dados da planilha de índice a partir do documento em pdf

### ISSUE THREAD

**Issue by JoaoVitorPereiraUFU** [ronaldoapf/PDS1#55]
## Como desenvolvedor desejo otimizar o processo de capitação dos dados da planilha de índice, com o intuito de deixar esta atividade otimizada.

> Existe a necessidade de retirar o trabalho manual por parte do usuário de gerar a planilha de índice em "csv", para otimizar o processo.

Critérios de Aceitação:
- Usuário seleciona arquivo pdf 
- Usuário seleciona diretório que será salvo os índices em formato .csv
- Sistema extrai os índices do arquivo pdf e salva em formato .csv no diretório de destino escolhido pelo usuário

Tarefas:
- [ ] Implementar interface em HTML para usuário informar o diretório do arquivo pdf e do diretório de destino que será salvo o .csv
- [ ] Implementar algoritmo para receber planilha em pdf e enviar ao back-end o diretório do arquivo que o usuário escolheu (1 hora)
- [ ] Implementar algoritmo para selecionar somente os índices contidos na planilha ( 2 horas)
- [ ] Decodificar dados da planilha a partir dos índices retirados da planilha (30 minutos)
- [ ] Implementar algoritmo em Python para enviar ao front-end a planilha que o usuário escolheu (já decodificada) em uma estrutura de dados (1 hora)

**Comment by Cardoso-CHM** [comment]
Está estória de usuário foi fechada porque a mesma não faz mais sentido para a aplicação, uma vez que não podemos garantir que a a estrutura dos próximos "pdfs" de documentação siga o mesmo formato do atual, se isso acontecer a fórmula de identificar os campos codificados não irá funcionar.
Agora será disponibilizado um treinamento para que o usuário utilize a aplicação conforme definido na estória 19
