### ISSUE TITLE
User Story 1: Efetuar estimativa de cálculo de IPTU

### ISSUE THREAD

**Issue by Cardoso-CHM** [ronaldoapf/PDS1#6]
## Como morador de Monte Carmelo desejo estimar a média de IPTU cobrado em meu setor com o objetivo de verificar se estou pagando um valor justo.

> Com a implementação do sistema os usuários finais terão mais embasamento para contestar o pagamento de uma guia de IPTU com valor que acreditam estar em desacordo.

### Critérios de Aceitação: 

- Usuário informa endereço do imóvel
- Informações do setor são listadas para usuário
- Exibir para usuário como o cálculo foi feito
- Listar na interface resultados obtidos

### Tarefas:
- [ ] Criar interface para o usuário localizar e utilizar o serviço de cálculo de IPTU ( 2 dias )
- [ ] Criar interface com formulário para usuário entrar com as informações necessárias para efetuar o cálculo ( 1 dia )
- [ ] Criar funcionalidade de pesquisa de endereços e dados necessários ( 7 dias )
- [ ] Criar algoritmo para estimar o cálculo do IPTU ( 1 dias )
- [ ] Criar interface para exibir resultados ( 1 dia )

**Comment by JoaoVitorPereiraUFU** [comment]
### Como adminstrador do aplicativo de setores desejo criar um mapa de setores para Monte Carmelo, com objetivo de agrupar as regiões da cidade.

Com a criação do mapa de setores a prefeitura terá grandes benefícios no que diz respeito a organização administrativa da cidade.

Critérios de Aceitação:
- Possibilidade de consultar itpu.
- Possibilidade de consultar m2 do terreno.
- Possiblidade de consultar contas de água, energia.

### Como empreendedor desejo saber o valor justo a ser pagar por um terreno, com o objetivo de melhorar o planejamento de compra de um terreno.

Com a implementação do sistema os usuários finais terão a possiblidade de consultar o valor do m2 do terreno, tanto para vende-lo ou para compra-lo, para assim fazer um melhor negócio.

Critérios de Aceitação:
- Possiblidade de consultar todos endereços possíveis.
- Possibilidade de consultar valor médio do m2 do lote.

**Comment by Cardoso-CHM** [comment]
Issue fechada por mudanças de requisitos
