### ISSUE TITLE
Como moradora da cidade de Monte Carmelo, gostaria de conferir em qual setor estou localizada para garantir que o endereço de minhas contas está correto.

### ISSUE THREAD

**Issue by amandadduraes** [ronaldoapf/PDS1#7]
Com a implementação do sistema os usuários finais poderão visualizar corretamente em qual setor determinado endereço está localizado.

Critérios de aceitação:
     - Listar setores da cidade
     - Visualizar localização dentro de um setor
     - Endereços podem ser pesquisados e encontrados no mapa de setor

**Comment by Cardoso-CHM** [comment]
Após a segunda reunião com a professora Luziane, podemos concluir que esta estória não está muito condizente com as funções idealizadas pela aplicação.

Segue link para minuta: https://github.com/ronaldoapf/PDS1/blob/master/docs/minutas/2019.09.09_%2015h00m_minuta2Luziane.md
