### ISSUE TITLE
User story 3: Visualizar preço do m² do setor

### ISSUE THREAD

**Issue by JoaoVitorPereiraUFU** [ronaldoapf/PDS1#9]
## Como empreendedor desejo saber o valor justo a ser pago por um terreno, com o objetivo de melhorar o planejamento de compra de um terreno.

> Com a implementação do sistema os usuários finais terão a possibilidade de consultar o valor do m2 do terreno, tanto para vende-lo ou para compra-lo, para assim fazer um melhor negócio.

Critérios de Aceitação:

- Possibilidade de consultar todos endereços possíveis.
- Possibilidade de consultar valor médio do m2 do lote.

### Tarefas:
- [ ] Promover interface para usuário entrar com endereço
- [ ] Coletar informações do usuário referente ao lote
- [ ] Efetuar busca de endereços (usuário seleciona apenas um)
- [ ] Cruzar dados no bancos com dados informados pelo usuário
- [ ] Efetuar cálculos com dados obtidos pelo usuário e do banco de dados
- [ ] Efetuar a consulta com base nos cálculos efetuados na tarefa anterior
- [ ] Mostrar informações referentes ao valor do terreno, com base no endereço selecionado

**Comment by Cardoso-CHM** [comment]
@JoaoVitorPereiraUFU Realizar correções
