### ISSUE TITLE
19.3 Criar, na seção 2 da página de tutoriais, uma explicação detalhada e exibindo prints, sobre como utilizar a aplicação

### ISSUE THREAD

**Issue by Cardoso-CHM** [ronaldoapf/PDS1#91]

**Comment by amandadduraes** [comment]
Feita no commit: https://github.com/ronaldoapf/PDS1/commit/17e20022b9ea89b0fb3805369199c32e31b3097f#diff-45f22b34dd0cb04e1b5f7c2dc2a16375
