### ISSUE TITLE
19.5 Na página "./_view/telaArquivos.html", inserir tooltip ao lado do select de índices

### ISSUE THREAD

**Issue by Cardoso-CHM** [ronaldoapf/PDS1#93]

**Comment by JoaoVitorPereiraUFU** [comment]
@Cardoso-CHM @ronaldoapf  achei que um tooltip não seria bom devido ao fato de que ele é muito pequeno e dificultaria para o usuário ler, neste caso utilizei um modal mesmo.

**Comment by Cardoso-CHM** [comment]
Task feita no seguinte commit: https://github.com/ronaldoapf/PDS1/commit/3e4f1d5186efeaeae45c0c6c4e114620eeeb5a36
